name: Build and Test SDK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test ElvahCharge scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build for Testing
        env:
          platform: iOS Simulator
        run: |
          # Pick the first available iPhone simulator
          device=$(
            xcrun xctrace list devices 2>&1 \
              | grep -oE 'iPhone.*?[^\(]+' \
              | head -1 \
              | awk '{$1=$1;print}' \
              | sed -e "s/ Simulator$//"
          )

          # Build tests for the ElvahCharge scheme
          xcodebuild build-for-testing \
            -scheme "ElvahCharge" \
            -testPlan "ElvahChargeTests" \
            -destination "platform=${platform},name=${device}"

      - name: Run Tests
        env:
          platform: iOS Simulator
        run: |
          # Pick the same simulator
          device=$(
            xcrun xctrace list devices 2>&1 \
              | grep -oE 'iPhone.*?[^\(]+' \
              | head -1 \
              | awk '{$1=$1;print}' \
              | sed -e "s/ Simulator$//"
          )

          # Run tests (without rebuilding) against the specified test plan
          xcodebuild test-without-building \
            -scheme "ElvahCharge" \
            -testPlan "ElvahChargeTests" \
            -destination "platform=${platform},name=${device}"
